#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EditorCommand {
    InsertChar(char),
    Backspace,
    Delete,
    MoveLeft { extend: bool },
    MoveRight { extend: bool },
    MoveWordLeft { extend: bool },
    MoveWordRight { extend: bool },
    MoveUp { extend: bool },
    MoveDown { extend: bool },
    Home { extend: bool },
    End { extend: bool },
    SelectAll,
    CancelSelection,
    Undo,
    Redo,
    Tab,
    Paste(String),
    StartBlockSelect { line: usize, col: usize },
    UpdateBlockSelect { line: usize, col: usize },
    EndBlockSelect,
    AddCursor { line: usize, col: usize },
    SetCursor { line: usize, col: usize },
    Click { line: usize, col: usize },
    ExtendSelection { line: usize, col: usize },
}
